name: Continuous Integration   # Name of the workflow. Its optional.
on:
  push:
    branchs: [main]
jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      -name: Greetings
       run: echo "Hello Github Actions!"
