name: Manual workflow
on:
  workflow_dispatch:  # it means this job need to run manually
jobs:
  manual-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Greetings
        run: echo "Hello Github Actions manual workflow!"
